### ISSUE TITLE
Cant run with elixir 1.6.4 and erlang 20.3

### ISSUE THREAD

**Issue by Preen** [holsee/chroxy#18]
```** (Mix) Could not start application chroxy: exited in: Chroxy.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            :erlang.binary_to_integer(nil)
            (chroxy) lib/chroxy/endpoint.ex:11: Chroxy.Endpoint.child_spec/0
            (chroxy) lib/chroxy/application.ex:29: Chroxy.Application.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4```

**Comment by holsee** [comment]
@Preen I have been meaning to update the dependencies to support the latest stable OTP (which is 21 IIRC).  This issue was due to the outdated version of the port libraries I was using, which did not have the support for OTP 21.  I have made a PR and will merge, and bump the version on hex shortly.

Thanks for the issue report, 👍 appreciated.
